### Read Entities
GET http://localhost:4004/beershop/

### $count=true
GET http://localhost:4004/beershop/Beers?$count=true

### $count
GET http://localhost:4004/beershop/Beers/$count

### Read Beers
GET http://localhost:4004/beershop/Beers
### Read Beers expanded to Brewery
GET http://localhost:4004/beershop/Beers?$expand=brewery
### Read Breweries
GET http://localhost:4004/beershop/Breweries
    ?$count=true
### Read Breweries filter with Lambda Operator any
GET http://localhost:4004/beershop/Breweries
    ?$count=true
    &$filter=beers/any(d:d/abv ge 5)
### Read Breweries filter with Lambda Operator all
GET http://localhost:4004/beershop/Breweries
    ?$count=true
    &$filter=beers/all(d:d/abv ge 5)
### Read Breweries expanded to Beers
# @name brewery
GET http://localhost:4004/beershop/Breweries?$expand=beers($filter=abv ge 5)
###
@breweryId = {{brewery.response.body.value[0].ID}}
### Create Beer with POST
# @name create
POST http://localhost:4004/beershop/Beers
Content-Type: application/json

{
    "ID": "{{$guid}}",
    "name": "Testbier with POST",
    "brewery_ID": "{{breweryId}}"
}
###
@id = {{create.response.body.ID}}
### Read Beer
GET  http://localhost:4004/beershop/Beers({{id}})
### Read Brewery expanded to Beers
GET http://localhost:4004/beershop/Breweries({{breweryId}})?$expand=beers($filter=ID eq {{id}})
### Delete Beer
DELETE  http://localhost:4004/beershop/Beers({{id}})

### Create Beer with PUT
PUT http://localhost:4004/beershop/Beers({{id}})
Content-Type: application/json

{
    "name": "Testbier with PUT"
}

### Deep Update
PUT http://localhost:4004/beershop/Breweries/4aeebbed-90c2-4bdd-aa70-d8eecb8eaebb
Content-Type: application/json

{
    "name": "Rittmayer Hallerndorfz",
    "beers": [
        {
            "name": "Weissen",
            "ibu": 55,
            "abv": 5.2
        }
    ]
}