# @fqdn = http://localhost:4004
@fqdn = https://4d3dc3fctrial-dev-cap-proj-srv.cfapps.eu10.hana.ondemand.com
###
# "reset" aka redeploy from csv
POST {{fqdn}}/beershop/reset
Content-Type: application/json

{}

###
# delete a brewery
DELETE {{fqdn}}/beershop/Breweries(0465e9ca-6255-4f5c-b8ba-7439531f8d28)