# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: [main]

jobs:
  build:
    # only run on non-ci commits 
    if: "!contains(github.event.head_commit.author.name, 'SAP Mentors & Friends')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm test

  publish-npm:
    # only run on non-ci commits 
    if: "!contains(github.event.head_commit.author.name, 'SAP Mentors & Friends')"
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.ADMIN}}
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: |
          git config --global user.name 'SAP Mentors & Friends'
          git config --global user.email 'sapmentors@users.noreply.github.com'
      # use standard-version for bumping versions in files,
      # and generating changelog
      # and tagging the release properly
      # and auto-incrementing the release number
      - run: npm run release
      # push to self aka main from within gh action with "release-state"
      # doesn't trigger this workflow again
      # b/c of missing personal access token here
      - run: git push --follow-tags origin main
      # finally publish the npm package
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
